blog/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "blog"

urlpatterns = [
    path('', Bloglist.as_view(), name="blog"),
    path('article/<slug:slug>', BlogDetailView.as_view(), name="blog-details"),
    path('category/<category_slug>/', PostList1.as_view(), name = 'post_list_by_category'),
]
handler404 = 'blog.views.error_404'
handler500 = 'blog.views.error_500'
handler500 = 'blog.views.error_403'

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # new
from django.urls import path, include # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('blogger/', admin.site.urls),
    path('', include('blog.urls'))
]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = "Mjournal Administrative site"
admin.site.site_title = "Mjournal Admin Portal"
admin.site.index_title = "Welcome to Mjournal's Administrative Portal"

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name="Title")
    slug = models.SlugField(unique=True, max_length=100, null=True)
    created = models.DateTimeField(auto_now_add = True, verbose_name = ('Created'), null=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def get_post_count(self):
        """ Returns amount of posts of this category """
        post_count = Blog.objects.filter(category = self).count()
        return(post_count)

    def get_absolute_url(self):
        return reverse('blog:post_list_by_category', args=[self.slug,])

    
    def __str__(self):
        return self.title
    
class Blog(models.Model):

    STATUS_CHOICES = (
        ('draft', ('Draft')),
        ('published', ('Published')),
    )


    Title = models.CharField(max_length=120)
    category = models.ForeignKey(Category, verbose_name="Category", on_delete=models.DO_NOTHING, null=True)
    image = models.ImageField(upload_to='image/blog/', null=False)
    textarea = RichTextField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft', verbose_name = ('Status'))
    publishedDate = models.DateTimeField(blank=True, null=True) 
    slug = models.SlugField(unique=True, max_length=100, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.Title
    
    @classmethod
    def blog_image(cls):
        image = cls.objects.all()

        return image

    def save(self, *args, **kwargs): # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog-details', kwargs={'slug': self.slug})

    _metadata = {
        'title': 'Title',
        'image': 'get_meta_image',
    }
    def get_meta_image(self):
        if self.image:
            return self.image.url

blog/views.py
from django.shortcuts import render
from .models import Blog
from django.utils import timezone
from django.shortcuts import render
from django.template import RequestContext
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category
from django.views.generic import ListView, DetailView
from django.http import Http404, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.apps import apps

# Create your views here.


#=================================================================


class Bloglist(ListView):
    template_name = "blog.html"
    model = Blog
    paginate_by = 8  
    context_object_name = 'post'


    def get_queryset(self):
        return self.model.objects.all().order_by('-publishedDate')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["trendings"] = self.model.objects.filter(publishedDate__month=timezone.now().month)[:3]
        return context

#=================================================================


class BlogDetailView(DetailView):
    model = Blog
    template_name = "blog-details.html"
    context_object_name = 'post'
    pk_url_kwarg = 'id'


    def get_object(self, queryset=None):
        obj = super(BlogDetailView, self).get_object(queryset=queryset)
        if obj is None:
            raise Http404("Blog does not exist")
        return obj

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            raise Http404("Blog does not exist")
        context = self.get_context_data(object= self.object)
        return self.render_to_response(context)



#=================================================================

class PostList1(ListView):
    template_name = 'post_list.html'
    model = Blog
    paginate_by = 8
    context_object_name = 'posts'

    def get_queryset(self, **kwargs):
        self.category = get_object_or_404(Category, slug=self.kwargs['category_slug'])
        posts=Blog.objects.filter(category=self.category.id)
        return Blog.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        context = super(PostList1, self).get_context_data(**kwargs)
        context['category'] = self.category
        return context



#======================================================================

def error_404(request, exception):
       
        return render(request,'404.html', data)

#=================================================================


def error_500(request):
        data = {}
        return render(request,'500.html', data)
        
#=================================================================



def error_403(request):
        data = {}
        return render(request,'404.html', data)

#=================================================================

templates/505.html
{% extends 'base.html' %}
{% load static %} 

{% block content %} 



{% endblock %}

templates/_categorieslist.html
{% load i18n %}
<!-- ==== Categories start ===== -->
<div class="card mt-0 mb-4">
    <h5 class="card-header">{% trans "Categories" %}</h5>
    <div class="card-body pl-0 pt-0 pr-0 pb-0">
        <ul class="list-group list-group-flush">
            {% for category in categories %}
                <li class="list-group-item d-flex justify-content-between align-items-center pl-4">
                    <a href="{{ category.get_absolute_url }}" class="text-dark">{{ category.title }}</a>
                     <span class="badge badge-secondary badge-pill">{{ category.get_post_count }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
<!-- ==== Categories end ==== -->

templates/_categoriessidelist.html
{% load i18n %}
<!-- ==== Categories start ===== -->
{% for category in categories %}
<li><a href="{{ category.get_absolute_url }}">{{ category.title }}</a></li>
{% endfor %}
<!-- ==== Categories end ==== -->

templates/base.html
{% load static %} 
{% load meta %}
{% load blog_tasks %}
<html lang="en">
   <head>
      <script data-ad-client="ca-pub-5511363389471594" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <meta name="description" content="">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="google-site-verification" content="9Brgu1IfpcmCWO8eFM5ic2S2D7KbMXHbFNG4bAluVoI" />
      <meta property="og:image" content={% if post %} "{% block og_image %}{{ request.scheme }}://{{ request.get_host }}{{ post.image.url }}{% endblock %}{% else %} "Mjournal" {% endif %}" />
      <meta property="og:title" content= {% if post %} '{{ post.Title }}' {% else %} "Mjournal" {% endif %} />
      <meta property="og:url" content= {% if post %} '{{ request.build_absolute_uri }}{{ post.image.url.get_absolute_url }}' {% else %} "Mjournal" {% endif %} />
      <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->
      <!-- Title -->
      <title>Mjournal - Informing the people</title>
      <!-- Favicon -->
      <link rel="icon" href="{% static 'img/core-img/logo.png' %}">
      <!-- Core Stylesheet -->
      <link rel="stylesheet" href="{% static 'style.css' %}">
   </head>
   <body>
      <!-- ##### Header Area Start ##### -->
      <header class="header-area">
         <!-- Top Header Area -->
         <div class="top-header-area">
            <div class="container">
               <div class="row">
                  <div class="col-12">
                     <div class="top-header-content d-flex align-items-center justify-content-between">
                        <!-- Logo -->
                        <div class="logo">
                           <a href="/"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- Navbar Area -->
         <div class="newspaper-main-menu" id="stickyMenu">
            <div class="classy-nav-container breakpoint-off">
               <div class="container">
                  <!-- Menu -->
                  <nav class="classy-navbar justify-content-between" id="newspaperNav">
                     <!-- Logo -->
                     <div class="logo">
                        <a href="index.html"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
                     </div>
                     <!-- Navbar Toggler -->
                     <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                     </div>
                     <!-- Menu -->
                     <div class="classy-menu">
                        <!-- close btn -->
                        <div class="classycloseIcon">
                           <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>
                        <!-- Nav Start -->
                        <div class="classynav">
                           <ul>
                              <li class="active"><a href="/">Home</a></li>
                              {% show_categories_side %}
                           </ul>
                        </div>
                        <!-- Nav End -->
                     </div>
                  </nav>
               </div>
            </div>
         </div>
      </header>
      <div class="popular-news-area section-padding-80-50">
         <div class="container">
            {% block content %} {% endblock %} 
         </div>
      </div>
      </div>
      </div>
      <!-- ##### Popular News Area End ##### -->
      <!-- ##### Footer Area Start ##### -->
      <footer class="footer-area">
         <!-- Main Footer Area -->
         <div class="main-footer-area">
            <div class="container">
               <div class="row">
                  <!-- Footer Widget Area -->
                  <div class="col-12 col-sm-6 col-lg-4">
                     <div class="footer-widget-area mt-80">
                        <!-- Footer Logo -->
                        <div class="footer-logo">
                           <a href="#"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
                        </div>
                        <!-- List -->
                     </div>
                  </div>
                  <!-- Footer Widget Area -->
               </div>
            </div>
         </div>
         <!-- Bottom Footer Area -->
         <div class="bottom-footer-area">
         </div>
      </footer>
      <!-- ##### Footer Area Start ##### -->
      <!-- ##### All Javascript Files ##### -->
      <!-- jQuery-2.2.4 js -->
      <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
      <!-- Popper js -->
      <script src="{% static 'js/bootstrap/popper.min.js' %} "></script>
      <!-- Bootstrap js -->
      <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
      <!-- All Plugins js -->
      <script src="{% static 'js/plugins/plugins.js' %}"></script>
      <!-- Active js -->
      <script src="{% static 'js/active.js' %}"></script>
      <script src="{% static 'js/scroller.js' %}"></script>
   </body>
</html>

templates/blog-details.html
{% extends 'base.html' %}
{% load blog_tasks %}
{% load static %} 
{% load blog_tasks %}
{% load social_share %}
{% block content %} 
<div class="row">
   <div class="col-12 col-lg-8">
      <div class="row">
         <div class="col-12 col-lg-12">
            <div class="blog-posts-area">
               <!-- Single Featured Post -->
               <div class="single-blog-post featured-post single-post">
                  <div class="post-thumb">
                     <a href="#"><img src="{{ post.image.url }}" alt="" style="width: 100%;"></a>
                  </div>
                  <div class="post-data">
                     <a href="#" class="post-catagory">{{ post.category }}</a>
                     <a href="#" class="post-title">
                        <h6>{{ post.Title }}</h6>
                        <p class="post-date">{{ post.published_date }}</span></p>
                     </a>
                     <div class="post-meta">
                        <p>{{ post.textarea | safe }}</p>
                        <div class="newspaper-post-like d-flex align-items-center justify-content-between">
                           <!-- Tags -->
                           <!-- Post Like & Post Comment -->
                           <div class="d-flex align-items-center post-like--comments">
                              <div class="entry__cat">
                                 <h5>Share on : </h5>
                                 <span class="entry__tax-list">
                                 {% post_to_twitter "New Article from MurangaJournal: {{ post.Title }}. Check it out!" object_or_url "Post to Twitter" %}
                                 {% post_to_whatsapp object_or_url "Share via WhatsApp" %}
                                 {% post_to_facebook object_or_url "Post to Facebook" %}
                                 </span>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
    <div class="col-12 col-lg-4">
        <!-- Corona Widget -->
        {% corona %}
        <!-- Popular news Widget -->
        {% show_latest_posts %}
    </div>
</div>
{% endblock %}

templates/blog.html
{% extends 'base.html' %}
{% load static %} 
{% load blog_tasks %}
{% block content %}        
{% slider_featured %}
</br>
</br>
<div class="row">
   <div class="col-12 col-lg-8">
      <div class="row">
         {% for post in post %}
         <!-- Single Post -->
         <div class="col-12 col-md-6">
            <div class="single-blog-post style-3">
               <div class="post-thumb">
                  <a href="{% url 'blog:blog-details'  post.slug %}"><img class='blogimg' src="{{ post.image.url }}" alt=""></a>
               </div>
               <div class="post-data">
                  <a href="{{ post.category.get_absolute_url }}" class="post-catagory">{{ post.category }}</a>
                  <a href="{% url 'blog:blog-details'  post.slug %}" class="post-title">
                     <h6>{{ post.Title }}</h6>
                  </a>
                  {% comment %} 
                  <div class="post-meta d-flex align-items-center">
                     <a href="#" class="post-like"><img src="img/core-img/like.png" alt=""> <span>392</span></a>
                     <a href="#" class="post-comment"><img src="img/core-img/chat.png" alt=""> <span>10</span></a>
                  </div>
                  {% endcomment %}
               </div>
            </div>
         </div>
         {% endfor %}
      </div>
   </div>
    <div class="col-12 col-lg-4">
        <!-- Corona Widget -->
        {% corona %}
        <!-- Popular news Widget -->
        {% show_latest_posts %}
    </div>

</div>

</br>
</br>
</br>
</br>

</br> </br>
{% if is_paginated %}   
<div class="pager d-flex align-items-center justify-content-between">
   {% if page_obj.has_previous %}
   <div class="prev">
      <a href="?page={{ page_obj.previous_page_number }}" class="active"><i class="fa fa-angle-left"></i> previous</a>
   </div>
   {% else %}
   {% endif %}
   {% if page_obj.has_next %}
   <div class="next">
      <a href="?page={{ page_obj.next_page_number }}">Next <i class="fa fa-angle-right"></i></a>
   </div>
   {% else %}
   {% endif %}
</div>
{% endif %}    
</section> <!-- end s-content -->
{% endblock %}

templates/corona.html
{% block content %}
                        <div class="popular-news-widget mb-50">
                            <h3>Live Covid-19 Updates Kenya</h3>

                            <!-- Single Popular Blog -->
                            <div class="single-popular-post">
                                <a href="#">
                                    <h6><span>Cornfirmed Cases</span> {{ Cases }}</h6>
                                </a>
                            </div>

                            <!-- Single Popular Blog -->
                            <div class="single-popular-post">
                                <a href="#">
                                    <h6><span>Today's Cases</span>{{ todayCases }} </h6>
                                </a>
                            </div>

                            <!-- Single Popular Blog -->
                            <div class="single-popular-post">
                                <a href="#">
                                    <h6><span>Total Deaths</span> {{ deaths }}</h6>
                                </a>
                            </div>

                            <!-- Single Popular Blog -->
                            <div class="single-popular-post">
                                <a href="#">
                                    <h6><span>Recovered Cases</span> {{ recovered }} </h6>
                                </a>
                            </div>
                        </div>
{% endblock  %}

templates/courosel.html
{% extends 'base.html' %}
{% load static %} 

{% for post in post|slice:":3" %}

    <section class="s-featured">
        <div class="row">
            <div class="col-full">                         


                <div class="featured-slider featured" data-aos="zoom-in">

                    <div class="featured__slide">
                        <div class="entry">
                            
                            <div class="entry__background" style="background-image:url('{{ post.image.url }}');"></div>
                            
                            <div class="entry__content">
                                <span class="entry__category"><a href="#0">{{ post.category }}</a></span>

                                <h1><a href="#0" title="">{{ trending.Title }}</a></h1>

                                <div class="entry__info">
                                    <ul class="entry__meta">
                                        
                                        <li>{{ post.published_date }}</li>
                                    </ul>
                                </div>
                            </div> <!-- end entry__content -->
                            
                        </div> <!-- end entry -->
                    </div> <!-- end featured__slide -->

                     <div class="featured__slide">

                        <div class="entry">
                            
                            <div class="entry__background" style="background-image:url('{{ post.image.url }}');"></div>
                            
                            <div class="entry__content">
                                <span class="entry__category"><a href="#0">{{ post.category }}</a></span>

                                <h1><a href="#0" title="">{{ trending.Title }}</a></h1>

                                <div class="entry__info">
                                    <ul class="entry__meta">
                                        
                                        <li>{{ post.published_date }}</li>
                                    </ul>
                                </div>
                            </div> <!-- end entry__content -->
                            
                    </div> <!-- end featured__slide -->

                    <div class="featured__slide">

                        <div class="entry">
                            
                            <div class="entry__background" style="background-image:url('{{ post.image.url }}');"></div>
                            
                            <div class="entry__content">
                                <span class="entry__category"><a href="#0">{{ post.category }}</a></span>

                                <h1><a href="#0" title="">{{ trending.Title }}</a></h1>

                                <div class="entry__info">
                                    <ul class="entry__meta">
                                        
                                        <li>{{ post.published_date }}</li>
                                    </ul>
                                </div>
                            </div> <!-- end entry__content -->
                            
                    </div> <!-- end featured__slide -->
                     
                </div> <!-- end featured -->

            </div> <!-- end col-full -->
        </div>
    </section> <!-- end s-featured -->

{% endfor %} 
{% block content %}
{% endblock %}

templates/post_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load blog_tasks %}
{% block content %}
<div class="row">
   <div class="col-12 col-lg-8">
      <div class="row">
         {% for post in posts %}
         <div class="col-12 col-md-6">
            <div class="single-blog-post style-3">
               <div class="post-thumb">
                  <a href="{% url 'blog:blog-details'  post.slug %}"><img class='blogimg' src="{{ post.image.url }}" alt=""></a>
               </div>
               <div class="post-data">
                  <a href="{{ post.category.get_absolute_url }}" class="post-catagory">{{ post.category }}</a>
                  <a href="{% url 'blog:blog-details'  post.slug %}" class="post-title">
                     <h6>{{ post.Title }}</h6>
                  </a>
               </div>
            </div>
         </div>
         {% endfor %}
      </div>
   </div>
    <div class="col-12 col-lg-4">
        <!-- Corona Widget -->
        {% corona %}
        <!-- Popular news Widget -->
        {% show_latest_posts %}
    </div>

</div>
{% endblock %}

templates/sideposts.html
<div class="popular-news-widget mb-50">
    <h3>Popular Articles</h3>
    {% for post in post_list %}
    <div class="single-blog-post small-featured-post d-flex">
        <div class="post-thumb">
            <a href="{% url 'blog:blog-details'  post.slug %}"><img src="{{ post.image.url }}" alt=""></a>
        </div>
        <div class="post-data">
            <a href="{{ post.category.get_absolute_url }}" class="post-catagory">{{ post.category }}</a>
            <div class="post-meta">
                <a href="{% url 'blog:blog-details'  post.slug %}" class="post-title">
                    <h6>{{ post.Title }}</h6>
                </a>
                <p class="post-date">{{ post.publishedDate }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

templates/slider.html
<div class="carousel">
   <div class="carousel__nav">
      <span id="moveLeft" class="carousel__arrow">
         <svg class="carousel__icon" width="24" height="24" viewBox="0 0 24 24">
            <path d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"></path>
         </svg>
      </span>
      <span id="moveRight" class="carousel__arrow" >
         <svg class="carousel__icon"  width="24" height="24" viewBox="0 0 24 24">
            <path d="M4,11V13H16L10.5,18.5L11.92,19.92L19.84,12L11.92,4.08L10.5,5.5L16,11H4Z"></path>
         </svg>
      </span>
   </div>
   {% for post in post_list %}
   <div class="carousel-item">
      <div class="carousel-item__image" style="background-image: url('{{ post.image.url }}');"></div>
      <div class="carousel-item__info">
         <div class="carousel-item__container">
            <h2 class="carousel-item__subtitle">{{ post.category }} </h2>
            <h1  class="carousel-item__title">{{ post.Title }}</h1>
            <p class="carousel-item__description">{{ post.textarea | safe | truncatechars:100 }}...</p>
            <a href="{% url 'blog:blog-details'  post.slug %}" class="carousel-item__btn">Read More</a>
         </div>
      </div>
   </div>
   {% endfor %}
</div>